language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION_LT=1.9
  - DJANGO_VERSION_LT=1.12
  - DJANGO_VERSION_LT=2.1
install:
  - pip install python-coveralls flake8 safety
  - pip install --pre "Django<$DJANGO_VERSION_LT"
script:
  - coverage run manage.py test
  - flake8 .
  - safety check
after_success:
  - coveralls
