language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION_LT=1.11
  - DJANGO_VERSION_LT=1.12
install:
  - pip install python-coveralls flake8
  - pip install --pre "Django<$DJANGO_VERSION_LT"
script:
  - coverage run manage.py test
  - flake8 .
after_success:
  - coveralls
